package vika.app.healthy_lifestyle.ui.theme.general

val emojiMap = mapOf(
    "" to "",
    "Без типа" to "",

    "Напиток" to "\uD83E\uDDC3",
    "Фрукт" to "\uD83C\uDF4F",
    "Сладкое" to "\uD83C\uDF6D",
    "Приправа" to "\uD83E\uDDC2",
    "Алкоголь" to "\uD83C\uDF77",
    "Дичь" to "\uD83D\uDC17",
    "Рыба" to "\uD83D\uDC1F",
    "Орех" to "\uD83C\uDF30",
    "Ягода" to "\uD83C\uDF47",
    "Вода" to "\uD83D\uDCA7",
    "Овощ" to "\uD83E\uDD55",
    "Мучное" to "\uD83C\uDF5E",
    "Зелень" to "\uD83E\uDD6C",
    "Соус" to "\uD83E\uDD6B",
    "Уксус" to "",
    "Мясо" to "\uD83C\uDF56",
    "Субпродукт" to "\uD83D\uDC3D",
    "Сыр" to "\uD83E\uDDC0",
    "Боб" to "\uD83E\uDEDB",
    "Крупа" to "\uD83C\uDF5A",
    "Гриб" to "\uD83C\uDF44",
    "Молочное" to "\uD83E\uDD5B",
    "Масло" to "\uD83E\uDDC8",
    "Яйцо" to "\uD83E\uDD5A",

    "Виды спорта" to "\uD83E\uDD3C",
    "Бег" to "\uD83C\uDFC3",
    "Езда на велосипеде" to "\uD83D\uDEB4",
    "Кондиционирующее упражнение" to "\uD83D\uDCAA",
    "Ходьба" to "\uD83D\uDEB6",
    "Бездействие" to "\uD83E\uDDCE",
    "Домашняя активность" to "\uD83E\uDDF9",
    "Садоводство" to "\uD83E\uDEB4",

    "Страх" to "\uD83D\uDE30",
    "Восхищение" to "\uD83D\uDE32",
    "Грусть" to "\uD83D\uDE2D",
    "Злость" to "\uD83D\uDE21",
    "Радость" to "\uD83D\uDE00",
    "Любовь" to "\uD83E\uDD70",
    "Отвращение" to "\uD83E\uDD22",
    "Интерес" to "\uD83E\uDDD0",
    "Стыд" to "\uD83D\uDE16"
)

val defaultOptionProduct = listOf(
    "Без типа",
    "Напиток",
    "Фрукт",
    "Сладкое",
    "Приправа",
    "Алкоголь",
    "Дичь",
    "Рыба",
    "Орех",
    "Ягода",
    "Вода",
    "Овощ",
    "Мучное",
    "Зелень",
    "Соус",
    "Уксус",
    "Мясо",
    "Субпродукт",
    "Сыр",
    "Боб",
    "Крупа",
    "Гриб",
    "Молочное",
    "Масло",
    "Яйцо"
)

val defaultOptionPhys = listOf(
    "Без типа",
    "Виды спорта",
    "Бег",
    "Езда на велосипеде",
    "Кондиционирующее упражнение",
    "Ходьба",
    "Бездействие",
    "Домашняя активность",
    "Садоводство"
)